### ISSUE TITLE
Merging $.fn.wTooltip.defaultSettings in the template?

### ISSUE THREAD

**Issue by uscore713** [geetarista/jquery-plugin-template#1]
Line 61 of the jquery.plugin-template.js file:

settings = $.extend({}, $.fn.wTooltip.defaultSettings, settings);

What is the rationale here?  Perhaps a copy-n-paste error?

**Comment by geetarista** [comment]
Yeah, it's a mistake. I think I was in the middle of refactoring and never actually finished. I'll push an update tonight with fixes. Thanks for the catch!
